#! /bin/bash

####################### LICENSE AND COPYRIGHT INFORMATION ########################

about-this-program () { cat <<EOF
================================================================================

                           CS:GO Multi Server Manager
                           --------------------------

   Launch and set up your Counter-Strike: Global Offensive Dedicated Servers.
   Report bugs, get more information and receive updates to this script at:

                $(printf "\x1b[36;1m%s\x1b[m"               "https://github.com/dasisdormax/csgo-multiserver")

--------------------------------------------------------------------------------

        Copyright (C) 2016 Maximilian Wende <maximilian.wende@gmail.com>

Licensed under the Apache License, Version 2.0 (the "License");  you may not use
this  file except in compliance  with the License. You may obtain a  copy of the
License at:
                   $(printf "\x1b[36;1m%s\x1b[m"            "http://www.apache.org/licenses/LICENSE-2.0")

Unless required by applicable law or agreed to in writing,  software distributed
under  the License  is distributed on  an "AS IS"  BASIS,  WITHOUT WARRANTIES OR
CONDITIONS  OF ANY KIND,  either  express or  implied.  See the  License for the
specific language governing permissions and limitations under the License.

================================================================================

EOF
}




################################### PROGRAM ###################################


# Get script filename and directory
basename="$(basename "${BASH_SOURCE[0]}")"
dirname="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
if [[ $PATH =~ (^|:)$dirname(:|$) ]]; 
	then THIS_COMM="$basename"; 
	else THIS_COMM="${BASH_SOURCE[0]}"; fi

THIS_SCRIPT="$(readlink -f "$dirname/$basename" 2> /dev/null)"
THIS_DIR="$(dirname "$THIS_SCRIPT")"
unset basename dirname

USER_DIR="$HOME/msm.d"


# override dot builtin: execute a file relative to the csgo-mulitserver base
# or the user's own msm settings directory
. () {
	if [[ -r "$USER_DIR/$cmd" ]] && ! [[ $1 =~ ^program/ ]]; then
		.. "$USER_DIR/$@"
	elif [[ -r "$THIS_DIR/$cmd" ]]; then
		.. "$THIS_DIR/$@"
	else return 1; fi
}

.. () {
	if [[ -d $1 ]]; then
		for file in "$1"/*.sh; do .. "$file"; done
	else
		local currentSrcDir="$(dirname $1)"
		builtin . "$1" ${@:2}; fi
}

# override colon builtin: execute a file relative to the current file's base directory
: () {
	local oldSrcDir="$currentSrcDir"
	local currentSrcDir="$oldSrcDir/$(dirname "$1")"
	builtin . "$oldSrcDir/$1"
}



. defaults.conf
. program/main.sh $@



errno=$?
unset -f . .. :
if [[ $0 != ${BASH_SOURCE[0]} ]]; then return $errno; else exit $errno; fi
