#! /bin/bash
## vim: noet:sw=0:sts=0:ts=4

# (C) 2016-2017 Maximilian Wende <dasisdormax@mailbox.org>
#
# This file is licensed under the Apache License 2.0. For more information,
# see the LICENSE file or visit: http://www.apache.org/licenses/LICENSE-2.0




App::generateServerConfig () (
	disclaimer () { cat <<-EOF; }
		// This file was generated by csgo-multiserver, licensed under the Apache License 2.0
		// See https://github.com/dasisdormax/csgo-multiserver for more information

	EOF

	MAPCYCLE_TXT="$INSTANCE_DIR/csgo/mapcycle.txt"
	AUTOEXEC_CFG="$INSTANCE_DIR/csgo/cfg/autoexec.cfg"
	SERVER_CFG="$INSTANCE_DIR/csgo/cfg/server.cfg"

	######## MAPCYCLE ########
	# The map pool (and usually its order as well) when using sourcemod

	rm "$MAPCYCLE_TXT"
	for map in ${MAPS[@]}; do
		echo "$map" >> "$MAPCYCLE_TXT"
	done



	######## AUTOEXEC ########
	# This is executed once when starting the server

	(
		disclaimer
		cat <<-EOF
			// -------- BASIC STUFF --------

			log on
			sv_password "$PASS"
			rcon_password "$RCON_PASS"

			hostname "$TITLE"
			${HOSTIP+"hostip \"$HOSTIP\""}
			${HOSTPORT+"hostport \"$HOSTPORT\""}

			sv_tags "$TAGS"

			// sv_lan should NEVER be set, because it disables VAC protection and
			// prevents loading of a player's inventory
			sv_lan 0

			sv_pure "$SV_PURE"
			sv_cheats "$SV_CHEATS"
			${SV_OCCLUDE_PLAYERS+"sv_occlude_players \"$SV_OCCLUDE_PLAYERS\""}

			exec banned_user.cfg // Read list of banned users
		EOF


		# GOTV specific settings ####
		(( TV_ENABLE )) && cat <<-EOF


			// -------- GOTV --------
			tv_advertize_watchable "${TV_ADVERTIZE_WATCHABLE-0}"
			tv_autorecord "${TV_AUTORECORD-0}"

			tv_password "$TV_PASS"
			tv_title "$TV_TITLE"

			tv_transmitall "$TV_TRANSMITALL"
			tv_relaytextchat "$TV_RELAYTEXTCHAT"
			tv_relayvoice "$TV_RELAYVOICE"

			${TV_CAMERAMAN+"tv_allow_camera_man_steamid \"$TV_CAMERAMAN\""}

			${TV_SPONSOR_IMAGE+"sv_server_graphic1 \"$TV_SPONSOR_IMAGE\""}
			${TV_HOST_IMAGE+"sv_server_graphic2 \"$TV_HOST_IMAGE\""}

			tv_delaymapchange 1
			tv_deltacache 2

			mapoverview_allow_client_draw 1
		EOF

		# Additional commands, may be set through the gamemode script
		for item in "${AUTOEXEC_ADDITIONAL[@]}"; do
			echo "$item"
		done
	) > "$AUTOEXEC_CFG"

	#### SERVER ####
	# This file is executed on every map change

	(
		disclaimer
		cat <<-EOF
			writeid // Update banned_user.cfg
			mp_maxplayers "$MAXPLAYERS"
			// You could add 'writeip' here, but banning ips is generally
			// not effective, with most people having dynamic ip addresses
		EOF

		# Additional commands, may be set through the gamemode script
		for item in "${SERVERCFG_ADDITIONAL[@]}"; do
			echo "$item"
		done
	) > "$SERVER_CFG"
)
